services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false
        bind:
            $adherentInterests: '%adherent_interests%'

    _instanceof:
        App\Mailchimp\Webhook\Handler\WebhookHandlerInterface:
            tags: ['app.mailchimp.webhook_handler']
        App\Mailchimp\Campaign\ContentSection\ContentSectionBuilderInterface:
            tags: [ 'app.mailchimp.campaign.content_builder' ]
        App\Mailchimp\Campaign\SegmentConditionBuilder\SegmentConditionBuilderInterface:
            tags: ['app.mailchimp.campaign.segment_condition_builder']
        Symfony\Component\Messenger\Handler\MessageHandlerInterface:
            tags: ['messenger.message_handler']

    App\Mailchimp\:
        resource: ../../src/Mailchimp/

    App\Mailchimp\Webhook\WebhookHandler:
        arguments: [!tagged 'app.mailchimp.webhook_handler']

    App\Mailchimp\Campaign\SegmentConditionsBuilder:
        arguments:
            $builders: !tagged 'app.mailchimp.campaign.segment_condition_builder'

    App\Mailchimp\Campaign\CampaignContentRequestBuilder:
        arguments:
            $builders: !tagged 'app.mailchimp.campaign.content_builder'

    App\Mailchimp\Synchronisation\Handler\AdherentChangeCommandHandler:
        tags:
            - { name: 'monolog.logger', channel: 'mailchimp_sync' }
        calls:
            - ['setLogger', ['@logger']]

    App\Mailchimp\Synchronisation\Handler\AdherentChangeEmailCommandHandler:
        tags:
            - { name: 'monolog.logger', channel: 'mailchimp_sync' }
        calls:
            - ['setLogger', ['@logger']]

    App\Mailchimp\Synchronisation\Handler\ElectedRepresentativeChangeCommandHandler:
        tags:
            - { name: 'monolog.logger', channel: 'mailchimp_sync' }
        calls:
            - ['setLogger', ['@logger']]

    App\Mailchimp\Synchronisation\Handler\DataSurveyCreateCommandHandler:
        tags:
            - { name: 'monolog.logger', channel: 'mailchimp_sync' }
        calls:
            - ['setLogger', ['@logger']]

    App\Mailchimp\Synchronisation\Handler\CoalitionContactChangeCommandHandler:
        tags:
            - { name: 'monolog.logger', channel: 'mailchimp_sync' }
        calls:
            - ['setLogger', ['@logger']]

    App\Mailchimp\Synchronisation\RequestBuilder:
        tags:
            - { name: 'monolog.logger', channel: 'mailchimp_sync' }
        calls:
            - ['setLogger', ['@logger']]

    App\Newsletter\Handler\:
        resource: ../../src/Newsletter/Handler/

    App\Mailchimp\SignUp\SignUpHandler:
        arguments:
            $client: '@app.http_client.mailchimp_signup'
            $subscriptionGroupId: '%env(MAILCHIMP_SIGNUP_SUBSCRIPTION_GROUP_ID)%'
            $subscriptionIds: '%env(json:MAILCHIMP_SIGNUP_SUBSCRIPTION_IDS)%'
            $mailchimpOrgId: '%env(MAILCHIMP_ORG_ID)%'
            $listId: '%env(MAILCHIMP_MEMBER_LIST_ID)%'
        tags:
            - { name: 'monolog.logger', channel: 'mailchimp_sync' }
        calls:
            - ['setLogger', ['@logger']]
