parameters:
    adherent_interests:
        ruralite: Ruralité
        solidarites: Solidarités
        culture: Culture
        economie: Economie
        education_et_jeunesse: Education et jeunesse
        egalite: Egalité F/H
        travail: Travail
        transition_ecologique: Transition écologique
        europe: Europe
        international: International
        justice: Justice
        numerique: Numérique
        sante: Santé
        securite: Sécurité
        democratie: Démocratie
        lgbtqi: LGBTQI+
        puissance_publique: Puissance Publique
        republique: République
        ville_et_quartier: Ville & Quartiers
        inclusion: Inclusion
