doctrine:
    dbal:
        driver:           pdo_pgsql
        charset:          UTF8
        host:             "%env(DATABASE_HOST)%"
        port:             "%env(DATABASE_PORT)%"
        dbname:           "%env(DATABASE_NAME)%"
        user:             "%env(DATABASE_USER)%"
        password:         "%env(DATABASE_PASSWORD)%"
        unix_socket:      "%env(DATABASE_SOCKET)%"
        server_version:   "13.1"
        platform_service: App\Doctrine\DBAL\Platform\PostgreSQLPlatform
        schema_filter:    '#^(?!(public|topology|tiger|rememberme_token))#'
        types:
            uuid:           Ramsey\Uuid\Doctrine\UuidType
            phone_number:   Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
            geo_point:      App\Doctrine\DBAL\Types\GeoPointType
            geometry:       CrEOF\Spatial\DBAL\Types\GeometryType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: false
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
            enabled:
                class:   App\Doctrine\Filter\EnabledFilter
                enabled: true

        dql:
            numeric_functions:
                ST_DISTANCESPHERE: App\Doctrine\Query\PostgreSQL\Spatial\STDistanceSphere
                ST_POINT: CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STPoint
                ST_WITHIN: CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STWithin
                ST_GEOMFROMTEXT: CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STGeomFromText
            string_functions:
                IN_ARRAY: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\InArray
                ANY_OF: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\Any
                STRING_TO_ARRAY: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\StringToArray
                ILIKE: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\Ilike
                UNACCENT: App\Doctrine\Query\PostgreSQL\Unaccent
                STRING_AGG: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\StringAgg
                POSITION: App\Doctrine\Query\PostgreSQL\Position
            datetime_functions:
                AT_TIME_ZONE: DoctrineExtensions\Query\Postgresql\AtTimeZoneFunction
                DATE_FORMAT: DoctrineExtensions\Query\Postgresql\DateFormat
        hydrators:
            EventHydrator: App\Doctrine\Hydrators\EventHydrator
