tests:
    "A page should take less than 150ms to render":
        path: '/.*'
        assertions:
            - 'main.wall_time < 150ms'

    "A page should take less than 10MB of memory":
        path: '/.*'
        assertions:
            - 'main.peak_memory < 10mb'

    "A page should use less than 10 SQL queries":
        path: '/.*'
        assertions:
            - 'metrics.sql.queries.count <= 10'

    "No Twig template should have been compiled at runtime":
        path: '/.*'
        assertions:
            - 'metrics.twig.compile.count == 0'

    "No Doctrine annotation or metadata should have been parsed at runtime":
        path: '/.*'
        assertions:
            - 'metrics.doctrine.annotations.parsed.count + metrics.doctrine.annotations.read.count + metrics.doctrine.entities.metadata.count + metrics.doctrine.dql.parsed.count == 0'
