version: "3.7"

services:
    ## en-marche.fr
    ###############
    app:
        networks:
            default:
                aliases:
                    - test.enmarche.code
                    - enmarche.code
        build: docker/dev
        depends_on:
            - db
            - redis
            - rabbitmq
        volumes:
            - .:/app

    db:
        image: mysql:5.7.25
        volumes:
            - ./docker/dev/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            MYSQL_DATABASE: enmarche
            MYSQL_ROOT_PASSWORD: root

    redis:
        image: redis:3.2-alpine

    ## testing
    ####################
    selenium:
        image: selenium/standalone-firefox-debug:2.53.1
        shm_size: 2g

    ## common
    ####################
    rabbitmq:
        image: rabbitmq:3-management-alpine




#    nginx:
#        build:
#            context: .
#            dockerfile: docker-new/nginx/Dockerfile
#            target: nginx
#        volumes:
#            - ./public:/app/public:ro
#        depends_on:
#            - fpm
#            - db
#            - redis
##            - rabbitmq
#        networks:
#            default:
#                aliases:
#                    - test.enmarche.code
#                    - enmarche.code
#        labels:
#            - 'traefik.enable=true'
#            - 'traefik.port=80'
#            - 'traefik.frontend.rule=Host:new.enmarche.code'

#    fpm:
#        build:
#            context: .
#            dockerfile: docker-new/php-fpm/Dockerfile
#            target: php-2
#        #            args:
#        #                - DEBUG_TOOLS=true
#        volumes:
#            - ./:/app
#        environment:
#            - APP_ENV=dev
#            - APP_DEBUG=1
