version: "2"

services:
    ## en-marche.fr
    ###############
    app:
        networks:
          default:
            aliases:
              - test.enmarche.code
              - enmarche.code
        build:
            context: docker/dev
        depends_on:
            - db
            - redis
            - rabbitmq
        volumes:
            - .:/app

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root

    redis:
        image: redis:3.2

    ## testing
    ####################
    selenium:
        image: selenium/standalone-firefox-debug:2.53.1
        volumes:
            - ./:/app

    ## common
    ####################
    rabbitmq:
        image: rabbitmq:3-management
