version: "2"

services:
    mysql:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: enmarche
            MYSQL_DATABASE: enmarche
            MYSQL_USER: enmarche
            MYSQL_PASSWORD: enmarche
        ports:
            - "3306:3306"

    tools:
        build: ./docker/tools
        depends_on:
            - mysql
        volumes:
            - .:/www
