security:

    role_hierarchy:
        ROLE_WRITER:
            - ROLE_APP_ADMIN_MEDIA_ALL
            - ROLE_APP_ADMIN_ARTICLE_ALL
            - ROLE_APP_ADMIN_LIVE_LINK_ALL
            - ROLE_APP_ADMIN_HOME_BLOCK_LIST
            - ROLE_APP_ADMIN_HOME_BLOCK_EDIT

        ROLE_ADMIN:
            - ROLE_WRITER
            - ROLE_APP_ADMIN_HOME_BLOCK_ALL

    access_decision_manager:
        strategy: unanimous

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    "%env(WRITER_LOGIN)%":
                        password: "%env(WRITER_PASSWORD)%"
                        roles: 'ROLE_WRITER'

                    "%env(ADMIN_LOGIN)%":
                        password: "%env(ADMIN_PASSWORD)%"
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            logout:
                path:   /admin/logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_WRITER }
